config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'jobs#index'

  resources :jobs do
    resources :resumes
  end

  namespace :admin do
    resources :jobs do
      member do
        post :publish
        post :hide
      end

      resources :resumes
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, presence: true
  validates :wage_upper_bound, presence: true
  validates :wage_lower_bound, presence: true
  validates :wage_lower_bound, numericality: { greater_than: 0 }

  scope :published, -> { where(:is_hidden => false) }
  scope :recent, -> { order("created_at DESC") }

  has_many :resumes

  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end
end

app/models/resume.rb
class Resume < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader

  validates :content, presence: true

  belongs_to :user
  belongs_to :job
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    is_admin
  end

  has_many :resumes
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :require_is_admin

  layout "admin"

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])

    if @job.update(job_params)
      redirect_to admin_jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to admin_jobs_path
  end

  def publish
    @job = Job.find(params[:id])
    @job.publish!
    redirect_back(fallback_location: admin_jobs_path)
  end

  def hide
    @job = Job.find(params[:id])
    @job.hide!
    redirect_back(fallback_location: admin_jobs_path)
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound,
                                :wage_lower_bound, :contact_email, :is_hidden)
  end
end

app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin

  layout "admin"

  def index
    @job = Job.find(params[:job_id])
    @resumes = @job.resumes.order('created_at DESC')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_is_admin
    if !current_user.admin?
      flash[:alert] = 'You are not admin'
      redirect_to root_path
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]

  def index
    case params[:order]
    when 'by_lower_bound'
      @jobs = Job.published.order("wage_lower_bound DESC")
    when 'by_upper_bound'
      @jobs = Job.published.order("wage_upper_bound DESC")
    else
      @jobs = Job.published.recent
    end
  end

  def show
    @job = Job.find(params[:id])

    if @job.is_hidden
      flash[:warning] = "This job already archieved"
      redirect_to root_path
    end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])

    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound,
                                :wage_lower_bound, :contact_email, :is_hidden)
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!

  def new
    @job = Job.find(params[:job_id])
    @resume = Resume.new
  end

  def create
    @job = Job.find(params[:job_id])
    @resume = Resume.new(resume_params)
    @resume.job = @job
    @resume.user = current_user

    if @resume.save
      flash[:notice] = "成功提交履历"
      redirect_to job_path(@job)
    else
      render :new
    end
  end

  private

  def resume_params
    params.require(:resume).permit(:content, :attachment)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
  def render_job_status(job)
    if job.is_hidden
      # <span class="fa fa-lock"></span>
      content_tag(:span, "", :class => "fa fa-lock")
    else
      # <span class="fa fa-globe"></span>
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end
end

app/helpers/admin/resumes_helper.rb
module Admin::ResumesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/jobs/_form.html.erb
<%= simple_form_for [:admin, @job] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :wage_lower_bound, :label => "薪资下限" %>
  <%= f.input :wage_upper_bound, :label => "薪资上限" %>
  <%= f.input :contact_email %>
  <%= f.input :is_hidden %>
  <%= f.submit "Submit", class: "btn btn-default" %>
<% end %>

app/views/admin/jobs/edit.html.erb
<h1>Edit a job</h1>
<%= render "form" %>

app/views/admin/jobs/index.html.erb
<div class="pull-right">
  <!-- 返回值为 /admin/jobs/new -->
  <%= link_to("Add a job", new_admin_job_path, :class => "btn btn-primary") %>
</div>

<table class="table">
  <thead>
    <tr>
      <td>职缺</td>
      <td>收到履历数量</td>
      <td>薪资下限</td>
      <td>薪资上限</td>
      <td>管理选项</td>
      <td>刊登时间</td>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td>
          <%= render_job_status(job) %>
          <%= link_to(job.title, admin_job_path(job)) %> <!-- /admin/jobs/:id -->
        </td>
        <!-- /admin/jobs/:job_id/resumes  -->
        <td><%= link_to(job.resumes.count, admin_job_resumes_path(job)) %></td>
        <td><%= job.wage_lower_bound %></td>
        <td><%= job.wage_upper_bound %></td>
        <td>
          <%= link_to("Edit", edit_admin_job_path(job)) %> |
          <%= link_to("Destroy", admin_job_path(job), :method => :delete,
                      :data => { :confirm => "Are you sure?"} ) %> |

          <% if job.is_hidden %>
            <%= link_to("Publish", publish_admin_job_path(job),
                        :method => :post,
                        :class => "btn btn-xs btn-default") %>
          <% else %>
            <%= link_to("Hide", hide_admin_job_path(job), :method => :post,
                        :class => "btn btn-xs btn-default") %>
          <% end %>
        </td>
        <td><%= job.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/jobs/new.html.erb
<h1>Add a job</h1>
<%= render "form" %>

app/views/admin/jobs/show.html.erb
<h1><%= @job.title %></h1>
<p><%= simple_format(@job.description) %></p>

app/views/admin/resumes/_resume.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-md-12">
        <h3 class="panel-title"><%= resume.user.email %></h3>
      </div>
    </div>
  </div>

  <div class="panel-body">
    <div class="trix-content">
      <p><%= simple_format(resume.content) %></p>
    </div>

    <hr>

    <% if resume.attachment.present? %>
      <i class="fa fa-paperclip"></i>
      <%= link_to("Download Resume", resume.attachment_url) %>
    <% else %>
      No attachment
    <% end %>
  </div>
</div>

app/views/admin/resumes/index.html.erb
<h2><%= @job.title %> - 履历列表</h2>
<hr>
<%= render :partial => "resume", :collection => @resumes, :as => :resume %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Job Demo</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to("注册", new_user_registration_path) %></li>
          <li><%= link_to("登录", new_user_session_path) %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>

            <ul class="dropdown-menu">
              <% if current_user.admin? %>
                <li><%= link_to("Admin Panel", admin_jobs_path) %></li>
              <% end %>
              <li><%= link_to("登出", destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  <!-- /.navbar-collapse -->
  </div>
<!-- /.container-fluid -->
</nav>

app/views/jobs/_form.html.erb
<%= simple_form_for @job do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :wage_lower_bound, :label => "薪资下限" %>
  <%= f.input :wage_upper_bound, :label => "薪资上限" %>
  <%= f.input :contact_email %>
  <%= f.input :is_hidden %>
  <%= f.submit "Submit", class: "btn btn-default" %>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit a job</h1>
<%= render "form" %>

app/views/jobs/index.html.erb
<div class="dropdown clearfix pull-right">
  <button class="btn btn-default dropdown-toggle" type="button"
          id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true">
    排序 <span class="caret"></span>
  </button>

  <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
    <li><%= link_to("按照薪资下限排序", jobs_path(:order => "by_lower_bound")) %></li>
    <li><%= link_to("按照薪资上限排序", jobs_path(:order => "by_upper_bound")) %></li>
    <li><%= link_to("按照发表时间排序", jobs_path) %></li>
  </ul>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <td>职缺</td>
      <td>薪资下限</td>
      <td>薪资上限</td>
      <td>刊登时间</td>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to(job.title, job_path(job)) %></td>
        <td><%= job.wage_lower_bound %></td>
        <td><%= job.wage_upper_bound %></td>
        <td><%= job.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/new.html.erb
<h1>Add a job</h1>
<%= render "form" %>

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>
<p><%= simple_format(@job.description) %></p>

<div class="text-center">
  <%= link_to("投交履历", new_job_resume_path(@job), :style => "font-size: 30px; text-decoration:underline;") %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>后台</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>

      <div class="row">
        <div class="col-md-2">
          <ul class="nav nav-pills nav-stacked" style="max-width: 300px; padding-top: 20px;">
            <li class="active"><%= link_to("Jobs", admin_jobs_path) %></li>
          </ul>
        </div>

        <div class="col-md-10">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/resumes/new.html.erb
<h3>投交履历到<%= @job.title %></h3>
<hr>

<%= simple_form_for [@job, @resume] do |f| %>
  <%= f.input :content %>
  <%= f.input :attachment %>
  <%= f.submit "送出", class: "btn btn-default" %>
<% end %>

app/views/welcome/index.html.erb
<h1> Hello World! </h1>